### ISSUE TITLE
error al usar una urls sin extensión

### ISSUE THREAD

**Issue by jansanchez** [jansanchez/css-url-versioner#3]
Al usar una url sin extensión, se corta la ejecución del paquete.

por ejemplo al usar un estilo así:

``` css
.home-company{
    color:#fff;
    background:url("iconLayout") helpCode no-repeat
}
```
